# Generated by Django 5.1.6 on 2025-02-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whalespecies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhaleSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date_sighted', models.DateTimeField(auto_now_add=True)),
                ('behaviour', models.TextField(max_length=350)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='whalespecies.whalespecies')),
            ],
        ),
    ]
