# Generated by Django 5.1.6 on 2025-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('whalesightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whalesighting',
            name='tags',
            field=models.ManyToManyField(related_name='sightings', to='tags.tag'),
        ),
    ]
